name: build

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: beeline-latest-binary.jar
          path: build/libs/beeline-*-binary.jar
          if-no-files-found: error

      #- run: ./gradlew uploadArchives
      #  if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'aitorvs/beeline' }}
      #  env:
      #    ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      #    ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/libs/beeline-*-binary.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set SHA
        id: shasum
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=sha::"$(shasum -a 256 build/libs/beeline-*-binary.jar | awk '{printf $1}')"

      - name: Bump Brew
        if: startsWith(github.ref, 'refs/tags/')
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_HOMEBREW_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          # Update to ensure we have the latest version which supports arbitrary default branches.
          brew update
          brew tap aitorvs/repo
          brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
            --sha256=${{ steps.shasum.outputs.sha }} \
            --url="https://github.com/aitorvs/beeline/releases/download/${{ steps.get_version.outputs.version }}/beeline-${{ steps.get_version.outputs.version }}-binary.jar" \
            aitorvs/repo/beeline
